[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Configurações para servir vídeos corretamente
[[headers]]
  for = "/video_depoimento/*"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
    Accept-Ranges = "bytes"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000"

# Configurações gerais de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirecionamentos
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200